### ISSUE TITLE
latest git npm start --production fails

### ISSUE THREAD

**Issue by mrneilypops** [unwitting/voolt#38]
`root@ubuntu-fra1-01:/var/www/voolt# npm start --production

> voolt@1.16.1 start /var/www/voolt
> node server.js

2016-11-06T12:58:46.541Z ::: Initialising config module
/var/www/voolt/cfg.js:49
  GOOGLE_ANALYTICS_ID: UA-86950105-1,
                       ^

ReferenceError: UA is not defined
    at Object.<anonymous> (/var/www/voolt/cfg.js:49:24)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/voolt/server_lib/cfg.js:21:13)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)

npm ERR! Linux 4.4.0-43-generic
npm ERR! argv "/root/.nvm/versions/node/v7.0.0/bin/node" "/root/.nvm/versions/node/v7.0.0/bin/npm" "start" "--production"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! voolt@1.16.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the voolt@1.16.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the voolt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs voolt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls voolt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/voolt/npm-debug.log
root@ubuntu-fra1-01:/var/www/voolt# 
`

**Comment by unwitting** [comment]
Wrap your config in a Javascript string:

```javascript
GOOGLE_ANALYTICS_ID = 'UA-86950105-1',
```

💃

**Comment by mrneilypops** [comment]
`root@ubuntu-fra1-01:/var/www/voolt# npm start --production

> voolt@1.16.1 start /var/www/voolt
> node server.js

2016-11-06T13:06:41.521Z ::: Initialising config module
/var/www/voolt/cfg.js:49
  GOOGLE_ANALYTICS_ID = 'UA-86950105-1',
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Invalid shorthand property initializer
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/voolt/server_lib/cfg.js:21:13)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)

npm ERR! Linux 4.4.0-43-generic
npm ERR! argv "/root/.nvm/versions/node/v7.0.0/bin/node" "/root/.nvm/versions/node/v7.0.0/bin/npm" "start" "--production"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! voolt@1.16.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the voolt@1.16.1 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the voolt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs voolt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls voolt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/voolt/npm-debug.log
root@ubuntu-fra1-01:/var/www/voolt# 
`

**Comment by unwitting** [comment]
You'll also need to define it as a JS object property: value with a colon, not equals:

```javascript
GOOGLE_ANALYTICS_ID: 'UA-61069916-5',
```

Sorry, should've caught that too in my first comment :D

**Comment by mrneilypops** [comment]
Up and running! after the above change. Thanks unwitting!
